# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'Build/Outside/WebApp/BuildOutside.csproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'Build/Outside/WebApp/BuildOutside.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'Build/Outside/WebApp/BuildOutside.csproj'
    arguments: '--configuration $(buildConfiguration)'
    zipAfterPublish: false
    modifyOutputPath: false

- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'fpommerening/ci-test'
    command: 'build'
    Dockerfile: 'Build/Outside/Dockerfile'
    buildContext: 'Build/Outside/WebApp/bin/Release/netcoreapp3.0/'
    tags: |
      $(Build.BuildId)
      latest
    addPipelineData: false

- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'fpommerening/ci-test'
    command: 'push'
    tags: |
      $(Build.BuildId)
      latest
    addPipelineData: false